### ISSUE TITLE
char2id时报错，AttributeError: Can't get attribute 'get_id' on <module '__main__' >

### ISSUE THREAD

**Issue by FinIoT** [yongyehuang/zhihu-text-classification#7]
@yongyehuang 你好!请问运行char2id时是否遇到过下面错误。
Processing eval data.
test question number 217360
There are 0 test questions without title.
100%|██████████| 217360/217360 [00:01<00:00, 151202.44it/s]
There are 55179 test questions without content.
100%|██████████| 55179/55179 [00:00<00:00, 56958.01it/s]
Exception in thread Thread-11:
Traceback (most recent call last):
  File "C:\Users\liks\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Users\liks\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\liks\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\multiprocessing\pool.py", line 463, in _handle_results
    task = get()
  File "C:\Users\liks\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\multiprocessing\connection.py", line 251, in recv
    return ForkingPickler.loads(buf.getbuffer())
AttributeError: Can't get attribute 'get_id' on <module '__main__' from 'C:\\Users\\liks\\AppData\\Local\\Continuum\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\spyder\\utils\\ipython\\start_kernel.py'>

**Comment by dragoncxl** [comment]
python3 map返回的不是list 需要将map返回的值转为list

**Comment by FinIoT** [comment]
@dragoncxl OK了，非常感谢，你是第一个回答我问题的，follow一下：）。 刚自学完深度学习重要原理，没啥编程基础，就是对着代码学python，坑多啊....
